In [1]:
import numpy as np
from sklearn import datasets

In [2]:
digits = datasets.load_digits()
X = digits.data
y = digits.target.copy()

# 手动构造倾斜数据，变成二分类问题
y[digits.target == 9] = 1
y[digits.target != 9] = 0

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=666)

In [8]:
from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)
y_predict = log_reg.predict(X_test)

C:\Users\IAdmin\Software\Dev_Tools\Anaconda\envs\imooc_ai\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
from sklearn.metrics import f1_score

f1_score(y_test, y_predict)

0.8674698795180723

In [10]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_predict)

array([[403,   2],
       [  9,  36]], dtype=int64)

In [12]:
from sklearn.metrics import precision_score

precision_score(y_test, y_predict)

0.9473684210526315

In [11]:
from sklearn.metrics import recall_score

recall_score(y_test, y_predict)

0.8

In [14]:
log_reg.decision_function(X_test)

array([-21.39899659, -32.89707466, -16.41659975, -79.82234371,
       -48.03358757, -24.18303848, -44.60835789, -24.24611413,
        -1.14253379, -19.00412796, -65.82243102, -50.9700369 ,
       -30.92218466, -45.94831743, -37.36164305, -29.51157105,
       -36.92920479, -82.80779538, -37.63444913,  -9.8796106 ,
        -9.26729695, -85.24973074, -16.74995021, -45.34477187,
        -5.02564401, -48.29612784, -11.6592453 , -37.36264786,
       -25.08303166, -13.59813044, -16.59626932, -28.78580416,
       -34.36703461, -28.52352512,  -8.1132276 ,  -4.6002956 ,
       -21.94666208, -21.87722506, -31.18063363, -23.36233873,
       -26.90528055, -62.23564508, -37.68783151, -66.36567876,
       -20.10286892, -16.68743885, -18.16651011, -21.54972463,
       -28.96561186, -19.61458655,   2.41072458,   7.73012017,
       -34.87319853, -42.70913446, -25.63117999, -34.75008042,
        -7.59793206, -49.51209245, -51.52643405,  19.66113943,
       -10.09498301, -32.00501078, -11.499299  ,  -1.42

In [15]:
log_reg.predict(X_test)[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
decision_scores = log_reg.decision_function(X_test)

In [17]:
np.min(decision_scores)

-85.72677329799792

In [18]:
np.max(decision_scores)

19.897029660621943

In [20]:
# 调整阈值，此时指标会变
y_predict_2 = np.array(decision_scores >= 5, dtype='int')

In [21]:
confusion_matrix(y_test, y_predict_2)

array([[404,   1],
       [ 21,  24]], dtype=int64)

In [22]:
precision_score(y_test, y_predict_2)

0.96

In [23]:
recall_score(y_test, y_predict_2)

0.5333333333333333

In [24]:
# 试试更低的阈值
y_predict_3 = np.array(decision_scores >= -5, dtype='int')

In [26]:
# 那么我们就知道，肯定也有类似于有个最优的平衡点
# 我们的任务就是寻找这个最优点
print(confusion_matrix(y_test, y_predict_3))
print(precision_score(y_test, y_predict_3))
print(recall_score(y_test, y_predict_3))

[[390  15]
 [  5  40]]
0.7272727272727273
0.8888888888888888
