In [1]:
import torch

In [2]:
# a 可以改变的
a = torch.ones(3)
print(a)
print(a[1])
print(float(a[2]))

a[0] = 6.2
print(a)

tensor([1., 1., 1.])
tensor(1.)
1.0
tensor([6.2000, 1.0000, 1.0000])


In [3]:
b = torch.tensor([1.2, 2.0, 3])
b

tensor([1.2000, 2.0000, 3.0000])

In [4]:
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])
print(points)
print(points.shape)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
torch.Size([3, 2])


In [5]:
# 切片操作也一样
print(points[1:])
print(points[0::2])

tensor([[5., 3.],
        [2., 1.]])
tensor([[4., 1.],
        [2., 1.]])


In [6]:
# 初始化 RGB 三通道张量数据
img_t = torch.randn(3, 5, 5) # 维度 channels, rows, columns
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [7]:
# 增加批量次数
batch_t = torch.randn(2, 3, 5, 5) # 维度 batch, channels, rows, columns

In [8]:
# 求平均值之类的操作
# 因为一个图片张量不一定只有 RGB 通道数据
# 但 RGB 通道数据一定在最后三列，故我们用-3求
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
print(img_gray_naive.shape)
print(batch_gray_naive.shape)

torch.Size([5, 5])
torch.Size([2, 5, 5])


In [9]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

print(batch_weights.shape)
print(batch_t.shape)
print(unsqueezed_weights.shape)

torch.Size([2, 3, 5, 5])
torch.Size([2, 3, 5, 5])
torch.Size([3, 1, 1])


In [11]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
print(weights_named)

tensor([0.2126, 0.7152, 0.0722], names=('channels',))


C:\Users\IAdmin\AppData\Local\Temp\ipykernel_10248\237186190.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ..\c10/core/TensorImpl.h:1903.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])


In [ ]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')